Run tests in release script

diff --git a/scripts/release b/scripts/release
--- a/scripts/release
+++ b/scripts/release
@@ -24,6 +24,21 @@ function autoincrement_tag() {
     echo "$major.$minor.$patch"
 }
 
+REPLY=""
+printf "\nRun Tests(Y)?\n>> "
+read
+if [ "$REPLY" = "y" ] || [ "$REPLY" = "Y" ]; then
+    printf "\n Running tests...\n"
+    npm run test
+    if [ ! "$?" = "0" ]; then
+        echo "Tests failed. Exiting..."
+        exit 1
+    fi
+else
+    printf "\nSkipping tests\n"
+fi
+REPLY=""
+
 if [ -z "$NEW_TAG" ]; then
     echo "No tag specified. Autoincrementing tag from $latest."
     NEW_TAG=$(autoincrement_tag)
